dist: xenial
language: java
jdk:
  - openjdk8
services:
  - mysql
before_script: mysql -h127.0.0.1 -uroot -e "drop database if exists demo; create database demo;"
script: ./gradlew build --info --stacktrace
